version: '3'

networks: 
  go-importer:
    driver: 'bridge'

services: 
  mysql: 
    image: mysql:5.7.22
    container_name: go_mysql
    restart: unless-stopped
    tty: true
    ports: 
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: go
      MYSQL_USER: go
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - go-importer